version: '3.8'

services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+mysqlconnector://app_user:SenhaSegura123!@db:3306/projetoteste
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projetoteste
      MYSQL_USER: app_user
      MYSQL_PASSWORD: SenhaSegura123!
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build: ./frontend
    ports:
      - "8080:80"

volumes:
  db_data:
